spring:
    h2:
        console:
            encoding: UTF-8
            enabled: true
            path: /h2-ui
    datasource:
        url: jdbc:h2:mem:testdb
        username: sa
        password: 
        driver-class-name: org.h2.Driver
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: update
    # datasource:
    #     url: jdbc:postgresql://localhost:5432/review
    #     username: postgres
    #     password: postgres
    # jpa:
    #     database-platform: org.hibernate.dialect.PostgreSQLDialect
    #     hibernate:
    #         ddl-auto: update